### ISSUE TITLE
Unbound module Type

### ISSUE THREAD

**Issue by miinguyen** [formalabstracts/CNL-CIC#1]
When I execute the command 'ocamlfind ocamlc -c -package sedlex -package batteries lexer_tex.ml', It return this err:

File "lexer_tex.ml", line 1, characters 5-9:
1 | open Type;;
         ^^^^
Error: Unbound module Type

How can I fix this? Thanks a lot.

**Comment by thalesant** [comment]
You should use dune to build the project, rather than ocamlfind.
